### PR TITLE
Adding API server support for service account

### PR DESCRIPTION
**Pull request by blublinsky**
## Checks

- [x] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by blublinsky** [comment]
This is a replacement for PR https://github.com/ray-project/kuberay/pull/1143. Something went wrong and I had to recreate
@kevin85421, @Jeffwan Sorry about the inconvenience, please use this one. I did addressed comments

**Comment by blublinsky** [comment]
@kevin85421 the only failure here is in /home/runner/work/kuberay/kuberay/./tests/compatibility-test.py"

**Comment by kevin85421** [comment]
Thank @blublinsky for this contribution! I have no prior experience with the KubeRay API Server. I will ask @Jeffwan to review this pull request.

**Comment by blublinsky** [comment]
@kevin85421, @Jeffwan already reviewed the original one and I fixed, what he asked

**Comment by kevin85421** [comment]
Hi @Jeffwan @scarlet25151, would you mind taking another look at this pull request? Thanks!

**Comment by blublinsky** [comment]
Added support for image pull secrets

**Comment by scarlet25151** [comment]
Hi @blublinsky thank you for your PR, the logic is LGTM. I just have one question that what the propose or usage for adding service account for each head pod?

**Comment by blublinsky** [comment]
As an afterthought also added support for image pull secret, which is required for using images from the private registry. That's what we are using extensively in IBM

**Comment by blublinsky** [comment]
@kevin85421 This was sitting for a while, can we please, commit it?

**Review by kevin85421 — APPROVED** [review]
I didn't review this PR, but one of the KubeRay API Server maintainers has approved it (https://github.com/ray-project/kuberay/pull/1148#issuecomment-1584890823).

**Pull request merged**
