### PR TITLE
Remove Docker from BasicRayTestCase

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?
Currently, some tests create docker containers to communicate with Kubernetes via a NodePort service. It is complex and unstable. Hence, this PR executes commands in the head Pod via `kubectl exec` instead of creating a docker container. See #764 for more details.

## Related issue number
Part of #764 

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by DmitriGekhtman — APPROVED** [review]
Removing the NodePort setup from these tests is a good idea.
We should make a note (issue) to have a dedicate test of Ray client, though.

Using a ClusterIP service and port-forwarding works reliably in the Ray CI, see
https://github.com/ray-project/ray/blob/d2e1ed6e70bfcf6ca355c1d0afbffe355b498405/python/ray/tests/kuberay/test_autoscaling_e2e.py#L329-L332

cc @wilsonwang371

**Comment by wilsonwang371** [comment]
I remember @brucez-anyscale  mentioned before that port-forwarding in kind might fail.

**Comment by DmitriGekhtman** [comment]
Perhaps it depends on the particular setup, but I have never seen Ray client port-forwarding fail in the Ray CI -- the particular test I've linked passes very consistently.

**Comment by wilsonwang371** [comment]
I pingged Bruce offline and see if he can make some comments here later. @brucez-anyscale

**Comment by kevin85421** [comment]
> Removing the NodePort setup from these tests is a good idea. We should make a note (issue) to have a dedicate test of Ray client, though.
> 
> Using a ClusterIP service and port-forwarding works reliably in the Ray CI, see https://github.com/ray-project/ray/blob/d2e1ed6e70bfcf6ca355c1d0afbffe355b498405/python/ray/tests/kuberay/test_autoscaling_e2e.py#L329-L332

QQ: why do we need to use port-forwarding when we have ClusterIP?

**Comment by DmitriGekhtman** [comment]
> QQ: why do we need to use port-forwarding when we have ClusterIP? In my understanding, we can create a Pod to communicate with the head Pod via ClusterIP directly.

That works fine as well.

**Pull request merged**
