### PR TITLE
[Refactor] Rewrite RayCluster envtest

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?

All tests in envtest couple together. This PR separates the old tests into 3 categories, autoscaling, static, and suspend. After this PR is merged, I will work on some tests for multi-host.

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kevin85421** [comment]
cc @rueian for review

**Comment by kevin85421** [comment]
cc @andrewsykim for the RayCluster suspend.

**Review by jjyao — APPROVED** [review]

**Comment by kevin85421** [comment]
@rueian @andrewsykim I will merge this PR without your review to unblock my release process. If you have any comments, I will address them in the follow-up PRs.

**Comment by andrewsykim** [comment]
> @rueian @andrewsykim I will merge this PR without your review to unblock my release process. If you have any comments, I will address them in the follow-up PRs.

Sorry for the late reply, LGTM!

**Comment by rueian** [comment]
LGTM too!

**Pull request merged**
