### PR TITLE
[Feature] host helm in github static site

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?
As mentioned by @Jeffwan in #475, we currently ask user to clone the KubeRay repo and then install helm chart. This is inconvenient and not the best practice for installation. Hence, we decided to use [helm/chart-releaser-action](https://github.com/helm/chart-releaser-action) to provide experience like:

```
helm repo add ray-project https://ray-project.github.io/kuberay
helm install kuberay ray-project/kuberay -n ray-system
```

When we push a commit to master branch, **helm/chart-releaser-action** will generate releases for all charts in `charts_dir: helm-chart` and update `index.yaml` in the GitHub page (the branch `gh-pages`). The `index.yaml` is necessary when you run the command `helm repo add`.

We use `needs: deploy` to make sure `deploy` finishes before `chart`. If `chart` finishes before `deploy`, `index.yaml` will be removed by MkDocs.

## Related issue number
#475 

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

This PR will only be triggered when pushing commits to `master` branch. Hence, I only tested this PR on my personal fork.

Screen Shot 2022-09-07 at 3 57 28 PM

### CODE REVIEW

**Comment by kevin85421** [comment]
cc @DmitriGekhtman @Jeffwan

**Comment by Jeffwan** [comment]
We host website in github static site. Can we overcome the conflict issue?

**Comment by DmitriGekhtman** [comment]
> We host website in github static site. Can we overcome the conflict issue?

Yep, was about to ask about this, here's the docs site https://ray-project.github.io/kuberay/
It seems this method would overwrite the docs.

Naive question: Why is it not possible to host multiple sites based on the same repo?

**Comment by kevin85421** [comment]
@Jeffwan @DmitriGekhtman Thank you for your comments!

You can check my [gh-pages](https://github.com/kevin85421/kuberay/tree/gh-pages) branch. The branch will have two commits.

1st commit: Deployed babde91 with MkDocs version: 1.3.1 => This commit is created by MkDocs.
2nd commit: Update index.yaml => This commit is created by [helm/chart-releaser-action](https://github.com/helm/chart-releaser-action) to create or update index.yaml.

You can check:
(1) https://kevin85421.github.io/kuberay/ => our website
(2) https://kevin85421.github.io/kuberay/index.yaml => our index.yaml

You can also test it with the following commands.
```bash
helm repo add my-chart https://kevin85421.github.io/kuberay/
helm install kuberay my-chart/kuberay-operator
```

**Comment by DmitriGekhtman** [comment]
Ah great, that makes sense!
So it seems that by running the chart action after the doc-building action we avoid the conflict.

This seems ok to me.

@Jeffwan what do you think?

**Review by DmitriGekhtman — APPROVED** [review]
Delaying the chart action to after the docs build makes sense as a work-around to use the helm-releaser action!
I'll merge this now -- we can always consider other options if for some reason someone complains :)

**Pull request merged**
