### PR TITLE
add priority and priorityClassName to ray-cluster template

### PR DESCRIPTION
**Pull request by walterddr**
## Why are these changes needed?

Similar to #181 we add priorityClassName and priority to the template

## Related issue number

N/A

## Checks

- [ ] I've made sure the tests are passing.
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by walterddr** [comment]
manually tested but not sure if i did the right thing. @kevin85421 any suggestions on how to move forward? thanks

**Comment by kevin85421** [comment]
cc @MortalHappiness would you mind reviewing this PR? Thanks!

**Comment by MortalHappiness** [comment]
LGTM

**Review by kevin85421 — APPROVED** [review]
Thanks

**Pull request merged**
