### PR TITLE
Flip Min and max replicas for apiserver workerNodeSpec

### LINKED ISSUE #1637: [Bug] [api-server] Min and max replicas flipped
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

apiserver

### What happened + What you expected to happen

The min and max replicas are flipped on this line: https://github.com/ray-project/kuberay/blob/1add258fcfd5c83319428355c0af4dde60ea9047/apiserver/pkg/model/converter.go#L195-L196

This causes issues when running get / list cluster methods on the python client. We run into this error:
```
     34     # Validate replicas
     35     if min_replicas > replicas:
---> 36         raise RuntimeError(f"min_replicas {min_replicas} is can't be greater then replicas {replicas} ")
     37     if replicas > max_replicas:
     38         raise RuntimeError(f"replicas {replicas} is can't be greater then max_replicas {max_replicas} ")

RuntimeError: min_replicas 2 is can't be greater then replicas 1 
```

The raw response from the API has the issue, not the python client.

### Reproduction script

Create a cluster with different min and max replicas, and get the cluster from the python client.

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by tedhtchang**
## Related issue number

closes #1637 

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [x ] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by smit-kiri** [comment]
Thanks!

**Review by z103cb — APPROVED** [review]
LGTM

**Review by blublinsky — APPROVED** [review]
LGTM

**Comment by blublinsky** [comment]
@kevin85421 pls merge

**Review by kevin85421 — APPROVED** [review]

**Pull request merged**
