### PR TITLE
bump controller-runtime to 0.11.1 and  Kubernetes to v1.23

### PR DESCRIPTION
**Pull request by chenk008**
## Why are these changes needed?

In kubeRay, we use controller-runtime to create K8s client, manage reconciler controllers. Currently we use `0.7.2`, it is incompatible with `logr v1.0.0`.  Bump the  `controller-runtime` to 0.11.1, it will be compatible with logr and help kubeRay to follow the version upgrade of the K8s community.

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by Jeffwan** [comment]
Let's hold this change until we release v0.2.0.  We pin stable version to 1.19 and that should work for cluster between 1.19-1.22

**Comment by Jeffwan** [comment]
We release v0.2.0 and this can be unblocked

**Comment by Jeffwan** [comment]
I update the title to include kubernetes which makes us easier to track changes later.

**Comment by Jeffwan** [comment]
The changes look good to me. Let's bump the version.

**Review by Jeffwan — APPROVED** [review]

**Comment by asm582** [comment]
@chenk008 @Jeffwan Thanks, I see two commits, should we squash the commits and merge this PR?

**Comment by Jeffwan** [comment]
> @chenk008 @Jeffwan Thanks, I see two commits, should we squash the commits and merge this PR?

We enable "Squash and merge" for the repo by default. :D

**Pull request merged**
