### PR TITLE
[Sample][autoscaler v2] Add sample yaml for autosclaer v2 

### PR DESCRIPTION
**Pull request by rickyyx**
## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rickyyx** [comment]
Oh is it because ray hasn't released yet: https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/3454#018e1b6f-1a44-455d-95f2-13c63684d786 ?

**Comment by rickyyx** [comment]
I see - so using nightly works. Maybe I will update this to be 2.10.0 once ray releases.

**Comment by rickyyx** [comment]
Update with `2.10.0`.

**Comment by kevin85421** [comment]
Would you mind rebasing with the master branch? Thanks!

**Comment by rickyyx** [comment]
ping for review @kevin85421

**Review by kevin85421 — APPROVED** [review]
Merge this PR. I will update the YAML in a follow up PR.

**Pull request merged**
