### PR TITLE
Add deploy manifests for apiserver

### LINKED ISSUE #88: [Feature][backend] Prepare Docker image and kubernetes manifest for service
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Backend service should be able to be deployed in the same cluster of ray-operator. We will need to prepare the manifest and dockerfile for the backend service. 

### Use case

_No response_

### Related issues

#54 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Jeffwan**
## Why are these changes needed?

With this change, user can easily deploy the kuberay apiserver.

## Related issue number

resolve #88 

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by wilsonwang371** [comment]
kuberay-apiserver is deployed together with kuberay-operator, right. Are we going to make a unified Makefile later?

**Comment by Jeffwan** [comment]
> kuberay-apiserver is deployed together with kuberay-operator, right? 

Yes. We should provide a kuberay control plane deployment guidance. It's documented in https://github.com/ray-project/kuberay/issues/114

> Are we going to make a unified Makefile later?

I think we don't need a unified Makefile since they are different modules now.

**Comment by Jeffwan** [comment]
Let's merge this one once #126 and #127 are merged

**Pull request merged**
