### PR TITLE
improve compatibility test stability

### PR DESCRIPTION
**Pull request by wilsonwang371**
## Why are these changes needed?

Sometimes the base compatibility test can fail. This might be related to exceptions not being handled correctly. 

## Related issue number

#294

## Checks

- [X] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [X] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by Jeffwan** [comment]
@wilsonwang371 Can we create an issue to discuss ray version coverage? 

I feel we can remove 1.9, 1.10, 1.11 and add 1.13?

**Comment by Jeffwan** [comment]
@wilsonwang371  Not sure if 1.13 works or not.. it runs ~1h 
image

**Comment by wilsonwang371** [comment]
> @wilsonwang371  Not sure if 1.13 works or not.. it runs ~1h 
> image
> 

i am waiting for the log to debug

**Comment by wilsonwang371** [comment]
> @wilsonwang371 Not sure if 1.13 works or not.. it runs ~1h image

This is due to 1.13.0 does not have redis python package installed. I corrected this part.

**Review by Jeffwan — APPROVED** [review]

**Pull request merged**
