### PR TITLE
ray-operator: Reuse contexts across ray operator reconcilers

### LINKED ISSUE #1089: Use context passed to the reconciler for operations instead of creating a new one using context.TODO() every time
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

In the current implementation of the operator, reconciler method a new context is created for every operation. According to https://www.makeuseof.com/go-contexts/ context.TODO() should be used as a placeholder when you need a context but no parent contexts are suitable. In the case of a reconciler, one is already provided, so it should be used instead of creating a new one every time.

### Use case

This might be useful for additional things that context supports, including parameters passing, context timeouts and deadlines

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by anishasthana**
cc @kevin85421 

## Related issue number

Closes #1089 

## Checks

- [x] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [x] Manual tests

I deployed using the instructions in development.md. I tested with the smallest sample: https://raw.githubusercontent.com/ray-project/kuberay/master/ray-operator/config/samples/ray-cluster.mini.yaml

### CODE REVIEW

**Comment by blublinsky** [comment]
Thanks @anishasthana

**Review by blublinsky — APPROVED** [review]

**Comment by kevin85421** [comment]
Thank you, @anishasthana, for this pull request, and thank you, @blublinsky, for raising this issue! It is a bit embarrassing, but I do not know much about `context`. 

* Will this change (replace `context.TODO` with the existing one) make operator have different behaviors?
* Would you mind adding more details about the advantages of using the existing context?

Thanks!

**Comment by blublinsky** [comment]
@kevin85421 A good description of context is here https://betterprogramming.pub/how-and-when-to-use-context-in-go-b365ddf42ae2. In a nutshell, propagating a context, instead of creating a new one every time conserves resources and allows an operator to better control the execution of the operator's sub/co routines

**Review by kevin85421 — APPROVED** [review]
LGTM! Thank @anishasthana for this contribution and @blublinsky for the review! The article is very helpful.

**Pull request merged**
