### PR TITLE
Build KubeRay Github site

### PR DESCRIPTION
**Pull request by Jeffwan**
1. Use Material for MkDocs to generate a site
2. Add ci job for site rendering
3. Create soft links for operator,apiserver and cli components
4. Add some new pages to enrich content of the new site

Some README.md are soft links
```
ln -s  ../../ray-operator/README.md operator.md
ln -s ../../apiserver/README.md apiserver.md
ln -s ../../cli/README.md cli.md
```

## Why are these changes needed?

This PR help create a Github site that organize all the existing docs together. This help user to easily onboard KubeRay project. 

## Related issue number

https://github.com/ray-project/kuberay/issues/212

## Checks

- [x] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by Jeffwan** [comment]
image

image

image

**Review by scarlet25151 — APPROVED** [review]
overall LGTM.

**Review by wilsonwang371 — APPROVED** [review]
LGTM

**Pull request merged**
