### PR TITLE
[Grafana] Use PodMonitor instead of ServiceMonitor for the Head Node to avoid metric duplication

### LINKED ISSUE #2502: [Feature] Multiple RayCluster CRs share the same Grafana
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

copy from https://ray.slack.com/archives/C02GFQ82JPM/p1730847604068249?thread_ts=1730408240.682809&cid=C02GFQ82JPM

In my ray cluster's metrics screen, i see metrics that are specific to my cluster, even though we have many ray clusters in our k8s cluster. However, if I click "view in grafana" in the top right corner, the corresponding grafana dashboard combines metrics from all ray clusters and sums them up. I want to add a filterable variable to the grafana dashboard to be able to set it to show me metrics for one cluster at a time.

I can do this for some of the panels by setting a filter on the `ray_io_cluster` field. However, other metrics don't appear to have a `ray_io_cluster` field to filter on.

Screenshot 2024-11-05 at 6 00 48 PM
Screenshot 2024-11-05 at 6 01 38 PM

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by win5923**
## Why are these changes needed?
Addresses: https://github.com/ray-project/kuberay/issues/2502#issuecomment-2495195658

This issue is caused by RayService. The Head Node is monitored using ServiceMonitor, while RayService creates two Services:

- One managed by RayService (e.g., rayservice-sample-head-svc)
- One managed by RayCluster (e.g., rayservice-sample-raycluster-6mj28-head-svc)

This results in the Head Node's metrics being duplicated. Switching to PodMonitor resolves this issue.

TODO:
- Update the Using Prometheus and Grafana doc.
Ref: https://docs.ray.io/en/latest/cluster/kubernetes/k8s-ecosystem/prometheus-grafana.html#step-5-collect-head-node-metrics-with-a-servicemonitor

image

Before:
image

After:
image

## Checks

- [x] I've made sure the tests are passing.
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by win5923** [comment]
@kevin85421 PTAL when you are free.

**Review by kevin85421 — APPROVED** [review]
Nice! Have you checked whether the Autoscaler/Dashboard metrics are being collected as expected?

**Review by kevin85421 — APPROVED** [review]
I manually tested it, and the Autoscaler/Dashboard metrics are as expected.

Screenshot 2024-12-27 at 12 07 05 PM
Screenshot 2024-12-27 at 12 06 50 PM

**Comment by win5923** [comment]
> I manually tested it, and the Autoscaler/Dashboard metrics are as expected.
> 
> 
> 
> Screenshot 2024-12-27 at 12 07 05 PM
> 
> Screenshot 2024-12-27 at 12 06 50 PM
> 
> 

Thanks!

**Pull request merged**
