### PR TITLE
Sync Helm chart CRDS

### PR DESCRIPTION
**Pull request by DmitriGekhtman**
Signed-off-by: Dmitri Gekhtman <dmitri.m.gekhtman@gmail.com>

## Why are these changes needed?

Closes https://github.com/ray-project/kuberay/issues/538 by syncing CRDs in Helm chart with CRDs in ray-operator config directory -- I ran
```
cp ray-operator/config/crd/bases/* helm-chart/kuberay-operator/crds/
```

Long-term potential solutions here are:
- Have the CI sync the CRDs
- Delete the CRDs in the ray-operator Helm chart, ask users to install the CRDs separately.

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kevin85421** [comment]
Does "synchronization" mean that the CRD in `helm-chart/kuberay-operator/crds` and CRD in `ray-operator/config/crd/bases/` should be the same?

If so, maybe we can `link` these two directories together like the YAML files in `docs/components/config/samples`.

Screen Shot 2022-09-07 at 4 40 48 PM

**Comment by DmitriGekhtman** [comment]
> Does "synchronization" mean that the CRD in helm-chart/kuberay-operator/crds and CRD in ray-operator/config/crd/bases/ should be the same?

Yes.

> If so, maybe we can link these two directories together like the YAML files in docs/components/config/samples.

Maybe -- but do you think that would cause any issues when we try to host the charts at a helm repository? (For example, will the CRDs be preserved when you `helm pull`?)

**Comment by Jeffwan** [comment]
soft link may bring some issue in packing senarios. We can add command in Makefile and probably add github actions to check whether before & after are same. If not, we force user to update using the same command on their side

**Comment by DmitriGekhtman** [comment]
> soft link may bring some issue in packing senarios. We can add command in Makefile and probably add github actions to check whether before & after are same. If not, we force user to update using the same command on their side

Doing the same thing in a pre-push hook would be convenient too.

**Comment by DmitriGekhtman** [comment]
Solving this in a permanent way is tracked in https://github.com/ray-project/kuberay/issues/446

@kevin85421 @Jeffwan, does this PR looks ok as a temporary fix?

**Review by kevin85421 — APPROVED** [review]
LGTM.

**Pull request merged**
