### PR TITLE
fix docs: typo in README.md

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Review by kevin85421 — APPROVED** [review]
Good catch! LGTM.

By the way, do you mind to validate some documents (grammar, clarity, accuracy of instructions) before release v0.4.0 (branch cut next week, and release next next week) if you are available? Feel free to change the field `REVIEWER` of any document that `STATUS` is empty to your name in this [spreadsheet](https://docs.google.com/spreadsheets/d/1wlTXCWNtQxCUENa0fP2-dV6UYNUhUCix4exiGsep5GQ/edit#gid=0). Thank you!

**Comment by davidxia** [comment]
Thanks, added myself to four rows. Lmk if you need more help than those. Feel free to merge this PR.

**Comment by kevin85421** [comment]
Thank @davidxia for your help!

**Comment by kevin85421** [comment]
Merge it because the doc modifications have no relationship with the CI failure.

**Pull request merged**
