### PR TITLE
Publish Multi Arch images

### LINKED ISSUE #1630: [Feature] Publish multi-architecture container images
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

The container images pushed in DockerHub and Quay are only for the `linux/amd64` architecture.

While it is possible to build container images for other architectures, these are not published, nor are the multi-architecture manifests.

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by tedhtchang**
## Why are these changes needed?

See #1630

## Related issue number

Closes #1630

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by astefanutti — APPROVED** [review]
LGTM

**Review by kevin85421 — COMMENTED** [review]
Greaaaaat! Just leave a minor comment. By the way, would you mind adding some instructions in [DEVELOPMENT.md](https://github.com/ray-project/kuberay/blob/master/ray-operator/DEVELOPMENT.md) about how to build multi-arch images locally? Thanks!

**Review by kevin85421 — APPROVED** [review]
Thanks! Let's merge it and check whether it publishes the multi-arch images successfully or not.

**Comment by kevin85421** [comment]
Nice!

Screen Shot 2023-12-08 at 9 33 04 AM

**Pull request merged**
