### PR TITLE
[Style] Fix golangci-lint rule: errorlint

### PR DESCRIPTION
**Pull request by MortalHappiness**
## Why are these changes needed?

Based on https://github.com/ray-project/kuberay/pull/2128, there are some rules that need manual fixing. This PR fixes the rule: `errorlint`

See https://golangci-lint.run/usage/linters/ for details.

## Related issue number

N/A

## Checks

- [x] I've made sure the tests are passing.
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by kevin85421 — COMMENTED** [review]
Can you fix https://github.com/ray-project/kuberay/actions/runs/9068220792/job/24915020733?pr=2141?

**Comment by MortalHappiness** [comment]
> Can you fix https://github.com/ray-project/kuberay/actions/runs/9068220792/job/24915020733?pr=2141?

See https://github.com/ray-project/kuberay/pull/2152

**Comment by kevin85421** [comment]
@MortalHappiness would you mind rebasing this PR with the master branch? Thanks

**Comment by MortalHappiness** [comment]
> @MortalHappiness would you mind rebasing this PR with the master branch? Thanks

Done

**Review by kevin85421 — APPROVED** [review]

**Pull request merged**
