### PR TITLE
Chore: upgrade to Golang 1.18

### PR DESCRIPTION
**Pull request by haoxins**
## Why are these changes needed?

The most important reason for using 1.18 is the __new Go workspace feature__ to work with multi-projects is especially useful.

## Checks

- [x] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by haoxins** [comment]
@Jeffwan any advice about the failed lint job?

**Comment by Jeffwan** [comment]
@haoxins  It's a little bit weird. Seems it failed at the step of "Run linter against ray operator" but error messages show `goimports` command was not found. Let me have a check

**Comment by Jeffwan** [comment]
@haoxins  It's a little bit weird. Seems it failed at the step of "Run linter against ray operator" but error messages show `goimports` command was not found. Let me have a check

**Comment by Jeffwan** [comment]
BTW, normally we upgrade golang version along with other kubexxx dependencies together. This is unnecessary but the conversion in this project. Let me check next kubernetes version we want to support and then come back to you on this.

**Pull request closed without merging**
