### PR TITLE
Build ray-operator for arm64

### PR DESCRIPTION
**Pull request by Tarpstone**
## Why are these changes needed?

Last week I attempted to install `kuberay` to a VM with `kubectl create -k "github.com/ray-project/kuberay/ray-operator/config/default?ref=${KUBERAY_VERSION}&timeout=90s"`, but the `kuberay-operator` crashed.

```
kuberay/ray-operator on  ray-operator-arm64-support [!] via 🐹 v1.17.6 took 10s 
❯ kubectl -n ray-system get pods                                                                                   
NAME                                READY   STATUS             RESTARTS      AGE
kuberay-operator-84487bc5c6-5jl44   0/1     CrashLoopBackOff   5 (14s ago)   3m10s

kuberay/ray-operator on  ray-operator-arm64-support [!] via 🐹 v1.17.6 
❯ kubectl -n ray-system logs kuberay-operator-84487bc5c6-5jl44
exec /manager: exec format error
```

I'm using an `arm64` VM, but it looks like the [latest image](https://hub.docker.com/r/rayproject/kuberay-operator/tags) is currently only built for `amd64`. These changes fixed my error, and should allow for building the operator image for multiple architectures.

## Related issue number

I'm not sure where this fits in with the roadmap described in https://github.com/ray-project/ray/issues/31966, but that's the closest related issue I could find.

## Checks

- [x] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

## Additional Info
Machine info:
Screenshot 2023-02-22 at 17 45 16

For kubernetes I'm using https://k3s.io/. I didn't do anything special, just ran their install script and then immediately tried to install kuberay operator on the clean cluster. Here's some of the output of `describe node`:
```
...
Roles:              control-plane,master
Labels:             beta.kubernetes.io/arch=arm64
                    beta.kubernetes.io/instance-type=k3s
                    beta.kubernetes.io/os=linux
                    egress.k3s.io/cluster=true
                    kubernetes.io/arch=arm64
                    ...
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/control-plane=true
                    node-role.kubernetes.io/master=true
                    node.kubernetes.io/instance-type=k3s
...
CreationTimestamp:  Fri, 17 Feb 2023 04:15:40 +0000
Taints:             <none>
Unschedulable:      false
...
System Info:
...
  Kernel Version:             5.15.0-1029-oracle
  OS Image:                   Ubuntu 20.04.5 LTS
  Operating System:           linux
  Architecture:               arm64
  Container Runtime Version:  containerd://1.6.15-k3s1
  Kubelet Version:            v1.25.6+k3s1
  Kube-Proxy Version:         v1.25.6+k3s1
PodCIDR:                      10.42.0.0/24
PodCIDRs:                     10.42.0.0/24
...
Non-terminated Pods:          (6 in total)
  Namespace                   Name                                       CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                       ------------  ----------  ---------------  -------------  ---
  kube-system                 svclb-traefik-dae6d056-4llts               0 (0%)        0 (0%)      0 (0%)           0 (0%)         5d18h
  kube-system                 traefik-66c46d954f-8wgp6                   0 (0%)        0 (0%)      0 (0%)           0 (0%)         5d18h
  kube-system                 coredns-597584b69b-nn9q7                   100m (10%)    0 (0%)      70Mi (1%)        170Mi (2%)     5d18h
  kube-system                 local-path-provisioner-79f67d76f8-xlz6g    0 (0%)        0 (0%)      0 (0%)           0 (0%)         5d18h
  kube-system                 metrics-server-5f9f776df5-tfstf            100m (10%)    0 (0%)      70Mi (1%)        0 (0%)         5d18h
  default                     kuberay-operator-6ffcf58478-h5fsn          100m (10%)    100m (10%)  512Mi (8%)       512Mi (8%)     3h3m
...
```

Here's a sample image after running the build for multiple architectures: https://hub.docker.com/layers/tarpstone/kuberay/v0.0.5/images/sha256-ba88924f23103514e1d4a76426e24c5eeb62a5d796cce6239fe5ed0c6d3d2071?context=repo

### CODE REVIEW

**Comment by kevin85421** [comment]
Oops. The Docker image in https://hub.docker.com/r/rayproject/kuberay-operator/tags is unmaintained and out-of-date. We currently maintain Docker images at https://hub.docker.com/r/kuberay/operator/tags. Btw, you can try to use the nightly Docker image.

In my Mac M1, the nightly Docker image works. Maybe you can try it on your development environment. In addition, for arm64 users, you need to use the Docker images for ARM. See [this doc](https://github.com/ray-project/kuberay/tree/master/helm-chart/ray-cluster) for more details.

**Comment by kevin85421** [comment]
Would you mind sharing which documents use the outdated Docker image? They should be updated. Thanks!

**Comment by Tarpstone** [comment]
Thanks Kevin -- when I follow the instructions in that doc, the operator itself still crashes. Is there a `nightly-aarch64` version of the operator somewhere that I'm missing?

(I think we're safe on outdated docs -- I couldn't find any so I must have just wandered into the wrong Docker page on my own!)

```
kuberay/ray-operator on  ray-operator-arm64-support via 🐹 v1.17.6 via 🐍 v3.11.2 (.venv) 
❯ helm install kuberay-operator kuberay/kuberay-operator --version 0.4.0 --set image.tag=nightly
NAME: kuberay-operator
LAST DEPLOYED: Wed Feb 22 14:27:55 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

kuberay/ray-operator on  ray-operator-arm64-support via 🐹 v1.17.6 via 🐍 v3.11.2 (.venv) took 2s 
❯ helm install raycluster kuberay/ray-cluster --version 0.4.0 --set image.tag=nightly-aarch64
NAME: raycluster
LAST DEPLOYED: Wed Feb 22 14:28:07 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

kuberay/ray-operator on  ray-operator-arm64-support via 🐹 v1.17.6 via 🐍 v3.11.2 (.venv) 
❯ kubectl get pods
NAME                                READY   STATUS             RESTARTS      AGE
kuberay-operator-56868578f7-5xn9x   0/1     CrashLoopBackOff   1 (17s ago)   18s

kuberay/ray-operator on  ray-operator-arm64-support via 🐹 v1.17.6 via 🐍 v3.11.2 (.venv) 
❯ kubectl logs pod/kuberay-operator-56868578f7-5xn9x
exec /manager: exec format error
```

**Comment by kevin85421** [comment]
Interesting. Thank @Tarpstone for pointing this out!

In that case, this PR is necessary. Would you mind adding more details to your PR description? For example,

(1) Development environment
(2) How did you test it?
(3) Screenshot or terminal output

Because I cannot reproduce the error on my Mac M1, I need more information before approval.

**Comment by Tarpstone** [comment]
No problem! @kevin85421 PR is updated with more info. The new Docker image should still work in current setups (I did also test it in the recommended `kind` cluster, but I haven't tested it on any other bare metal setups yet).

**Comment by kevin85421** [comment]
CI fails. Maybe we need to update https://github.com/ray-project/kuberay/blob/master/.github/workflows/test-job.yaml#L235-L245.

**Comment by Tarpstone** [comment]
Think I've got it...we needed to explicitly `--load` these into Docker now that we're using buildx. I'll have this up shortly.
```
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache.
To push result image into registry use --push or to load image into docker use --load
```

**Comment by kevin85421** [comment]
CI fails to load the Docker image into the Kind cluster. If you want to run the compatibility tests ("Compatibility Test - x.x.x") on your laptop, you can refer to https://github.com/ray-project/kuberay/blob/master/ray-operator/DEVELOPMENT.md#run-end-to-end-tests-locally. 

```sh
subprocess.CalledProcessError: Command 'kind load docker-image kuberay/operator:ecafe02' returned non-zero exit status 1.

```

**Comment by Tarpstone** [comment]
Strange - it loads into a local kind cluster just fine when running the e2e tests. I'll take a look at the image artifact.

**Comment by Tarpstone** [comment]
The issue here is with `docker save`. It's apparently less than fully compatible with multi-architecture images. If you download the `.tar` artifact locally and try to inspect the manifest you'll get:
```
kuberay-actions on  main [?]
❯ docker manifest inspect kuberay/operator:ecafe02
no such manifest: docker.io/kuberay/operator:ecafe02
```

This seems to be why kind is failing to load the image. Unfortunately I haven't found the "correct" solution for a local save of a multi-architecture image. One example that doesn't work:
```
docker buildx build --platform linux/amd64,linux/arm64 --output "type=docker,push=false,dest=operator_local.tar" .
[+] Building 0.0s (0/0)                                                                                                                                  
ERROR: docker exporter does not currently support exporting manifest lists
```

**Comment by Tarpstone** [comment]
Thanks -- that `tar` output type also doesn't work (you basically get the filesystem as output, no image manifest or layers), but it did help me realize that the compatibility tests were grabbing the `arm64` image instead of the `amd64` one.

I added a basic outline of how we can specify which image to grab for testing for now...but I can imagine at some point we might want to test both in the pipeline. I think this would require more changes.

**Comment by nicklausbrown** [comment]
Is this still being worked on actively? I've got interest in running kuberay on my HA control plane for K3s which is composed of orange-pi 5 plus nodes.

**Comment by kevin85421** [comment]
@nicklausbrown Thank you for the follow-up! This PR is not currently active. If there are many requests regarding ARM chips, I may prioritize them after the Ray summit.

**Comment by holdenk** [comment]
Also interested in this happy to take it over. I've got a dual arm64/amd64 cluster I run kube on.

**Comment by kevin85421** [comment]
@holdenk, this would be great! Initially, I suggest providing scripts & docs to enable users to build the ARM image on their own in the first few PRs. Following that, we can begin working on the CI integration.

**Comment by kevin85421** [comment]
cc @pingsutw

**Comment by kevin85421** [comment]
#1716

**Pull request closed without merging**
