### PR TITLE
add kuberay on kind jupyter notebook

### PR DESCRIPTION
**Pull request by wilsonwang371**
## Why are these changes needed?

Add a jupyter notebook about how to setup a kuberay cluster on local kind environment

## Related issue number

N/A

## Checks

- [X] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(
   - [X] Not needed

### CODE REVIEW

**Comment by Jeffwan** [comment]
I have one more comment on the tutorial. I think user may be interested in the way to submit workloads to the cluster.  10001 port, can we add some guidance on where to retrieve the endpoint and how to verify connectivity is ok like below?

```
ray.util.connect('address')
```

**Comment by wilsonwang371** [comment]
> I have one more comment on the tutorial. I think user may be interested in the way to submit workloads to the cluster. 10001 port, can we add some guidance on where to retrieve the endpoint and how to verify connectivity is ok like below?
> 
> ```
> ray.util.connect('address')
> ```

I made some changes to the notebook.

**Comment by Jeffwan** [comment]
image

@wilsonwang371 Since controller already creates the service, is there a way we can avoid duplicate service creation?  I think extra port mapping should be enough for user to connect from localhost?

https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings

**Comment by wilsonwang371** [comment]
> image
> 
> @wilsonwang371 Since controller already creates the service, is there a way we can avoid duplicate service creation? I think extra port mapping should be enough for user to connect from localhost?
> 
> https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings

We discussed this in #157. This service is needed for redirecting traffic from kind nodeport to kuberay.

**Review by Jeffwan — APPROVED** [review]

**Pull request merged**
