### PR TITLE
[Helm] Expose security context in helm chart.

### PR DESCRIPTION
**Pull request by DmitriGekhtman**
Signed-off-by: Dmitri Gekhtman <dmitri.m.gekhtman@gmail.com>

## Why are these changes needed?

Exposes securityContext in Helm charts.
See https://github.com/ray-project/kuberay/pull/750.

TODO: Test with the workflows in https://github.com/ray-project/kuberay/pull/750

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by DmitriGekhtman** [comment]
cc @juliusvonkohout

**Comment by juliusvonkohout** [comment]
I only took a glimpse, but is the naming really consistent?

**Comment by DmitriGekhtman** [comment]
> I only took a glimpse, but is the naming really consistent?

I'm open to suggestions!

My main consideration when making changes to these charts is backwards compatibility.
I'm not 100% pleased with the previous decisions that were made, but for now I'm just trying to expose the necessary configuration while keeping things consistent with what's already there.

**Comment by DmitriGekhtman** [comment]
> I only took a glimpse, but is the naming really consistent?

Basically, I'm saying 
"No, the naming is not completely consistent. But it's the best I can do at the moment."

**Comment by juliusvonkohout** [comment]
Alright, then why do we not take the values from the other PR instead of initContainerSecurityContext: {}?

**Comment by DmitriGekhtman** [comment]
> Alright, then why do we not take the values from the other PR instead of `SecurityContext: {}`?

I'd prefer to simply expose the configuration rather than copying it everywhere.

**Comment by DmitriGekhtman** [comment]
> > Alright, then why do we not take the values from the other PR instead of `SecurityContext: {}`?
> 
> I'd prefer to simply expose the configuration rather than copying it everywhere.

Actually, sure -- I'll set the defaults to the recommended securityContext and then let users override as needed.

**Comment by DmitriGekhtman** [comment]
> > > Alright, then why do we not take the values from the other PR instead of `SecurityContext: {}`?
> > 
> > 
> > I'd prefer to simply expose the configuration rather than copying it everywhere.
> 
> Actually, sure -- I'll set the defaults to the recommended securityContext and then let users override as needed.

Will repeat the same treatment for the auto-configured autoscaler container.

**Comment by DmitriGekhtman** [comment]
> Alright, then why do we not take the values from the other PR instead of `SecurityContext: {}`?

Actually, never mind.

The reason for not doing this by default is

1. It makes debugging more difficult for infra developers.
2. It appears at the moment to interact poorly with OpenShift.

Thus, it's better to clearly document the security context recommendation, but not to copy the more restrictive configuration everywhere.

**Comment by DmitriGekhtman** [comment]
Thanks, @juliusvonkohout for prodding us to ensure that Ray can run on Kubernetes with proper security configuration!

**Comment by DmitriGekhtman** [comment]
@kevin85421 this works exactly as expected when the relevant securityContext configuration is added.
It fails exactly as expected when the relevant securityContext configuration is removed.

**Review by kevin85421 — APPROVED** [review]
LGTM

**Pull request merged**
