### PR TITLE
[Feature] Expose initContainer image in RayCluster chart

### LINKED ISSUE #673: [Feature] ray-cluster: add busybox image to values
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

please add busybox image to https://github.com/ray-project/kuberay/blob/master/helm-chart/ray-cluster/values.yaml as variable. 
now it's hardcoded in ray-cluster template in this way:
        initContainers:
          - name: init-myservice
            image: busybox:1.28
So that it will be better to store image name and tag in values file.

### Use case

this change can provide possibility to run ray-cluster in argocd using repository path override to private repository. In this case it will not be necessary to pull busybox image from public repository

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?
Some users hope to pull the busybox images from private repositories. Hence, this PR makes the image field of init container become configurable in the RayCluster helm chart.

Q1: Is it possible for us to have multiple init containers?
Q2: Is it possible to expose other fields for init containers? See [k8s doc](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container) for other container fields.

## Related issue number
Closes #673 

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

## Manual tests
* `worker.initContainerImage` and `smallGroup.initContainerImage` (commented out `disabled: true`) are defined.
* `worker.initContainerImage` and `smallGroup.initContainerImage` (commented out `disabled: true`) are undefined.

### CODE REVIEW

**Comment by kevin85421** [comment]
cc @ivan-yaromka

**Comment by kevin85421** [comment]
We need to figure out Q1 and Q2 to decide how to expose the interface for `initContainers`. Any thoughts? Thanks!

cc @DmitriGekhtman @Jeffwan

**Comment by Jeffwan** [comment]
private registry makes sense.  I am trying to understand the if there're valid cases for Q1 and Q2?

**Comment by DmitriGekhtman** [comment]
This is fine.
Later on, we need to refine the initialization sequence: https://github.com/ray-project/kuberay/issues/476

**Review by DmitriGekhtman — APPROVED** [review]

**Pull request merged**
