### PR TITLE
[Grafana] Update Grafana dashboard

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?

1. Upgrade the Ray Grafana dashboard from 2.5.0 to 2.9.0.
2. Add the Grafana dashboards for Ray Data / Ray Serve.

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
What's the context of this PR?

**Comment by kevin85421** [comment]
> What's the context of this PR?

Currently, the Ray dashboard generates Grafana dashboard configurations at runtime. From my perspective, this is unusual behavior. Consequently, users need to copy the JSON configurations from the Ray head Pod and paste them into Grafana to create the dashboard. As a workaround, I also maintain a JSON configuration that users can directly use when following the Ray documentation.

**Review by jjyao — APPROVED** [review]

**Comment by kevin85421** [comment]
Convert it to draft. I will update the config to Ray 2.20 after I update the sample YAMLs to use Ray 2.20 images.

**Comment by kevin85421** [comment]
Ray 2.20.0 has some issues, so I will not upgrade KubeRay to use Ray 2.20.0 by default. See https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1714683469966249 for more details. Merge this PR.

**Pull request merged**
