### PR TITLE
updating url use v1

### PR DESCRIPTION
**Pull request by blublinsky**
## Why are these changes needed?
As we are gearing to v1 this PR updates API server URLs to reflect V1

All proto files are updated to use V1 in URL. Additionally test files and readme were updated to reflect this change

## Checks

- [ x] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by blublinsky** [comment]
@z103cb, @tedhtchang, @astefanutti pls, take a look

cc: @kevin85421

**Review by z103cb — APPROVED** [review]
LGTM

**Review by tedhtchang — COMMENTED** [review]
@blublinsky 4 file still have the the v1alpha2 curl examples.  Do we need to change these?
./test/service/service:curl 'localhost:8888/apis/v1alpha2/namespaces/default/services' \
./test/service/service:curl 'localhost:8888/apis/v1alpha2/services' \
./test/service/service:curl -X DELETE localhost:8888/apis/v1alpha2/namespaces/default/services/test-v2
./test/service/serviceV1:curl -X POST 'localhost:8888/apis/v1alpha2/namespaces/default/services' \
./test/service/serviceV2:curl -X POST 'localhost:8888/apis/v1alpha2/namespaces/default/services' \
./test/job/query:curl -X GET 'localhost:8888/apis/v1alpha2/namespaces/default/jobs' \
./test/job/query:curl -X GET 'localhost:8888/apis/v1alpha2/jobs' \
./test/job/query:curl -X GET 'localhost:8888/apis/v1alpha2/namespaces/default/jobs/job-test' \
./test/job/query:curl -X DELETE 'localhost:8888/apis/v1alpha2/namespaces/default/jobs/job-test' \

**Comment by blublinsky** [comment]
Thanks @tedhtchang for catching this. fixed

**Comment by blublinsky** [comment]
@kevin85421  I think this one is ready for commit

**Review by kevin85421 — APPROVED** [review]
I rerun the failed CI tests. I will merge this PR when CI passes.

**Pull request merged**
