### PR TITLE
[WIP] Allow setting custom cluster name

### LINKED ISSUE #1294: [Feature] Allow setting the RayClusterName in the job specification to have determinitic service head
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently in order to expose the service to the end user, we need to look for the service name which contains a random number.

For instance of the user has already a unique RayJob: `job-22f1d24aff9a4c7fbe5ab9707decbcb0` the cluster name would something like this `job-22f1d24aff9a4c7fbe5ab9707decbcb0-raycluster-7ct2d` and subsequently the service head would be `22ff9a4c7fbe5ab9707decbcb0-raycluster-7ct2d-head-svc`.

It would be nice to allow the user to set the value and only generate them if not specified.

### Use case

I understand the logic to prevent crashing the creation of the cluster, unfortunately this make using the operator very hard.

I think the specification should allow setting the RayClusterName similar to the JobId to allow building on top of this operator.

**Note**: I already tried to set the name of the service and head via `metadata.name` unfortunately some env vars are auto generated and the ray params and using the env var to resolve the service name.

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by mmourafiq**
@architkulkarni @kevin85421 

## Why are these changes needed?

This PR extends the RayJob CRD with a `RayClusterName` field with similar behavior to `JobId`.

## Related issue number

Closes #1294 

## Checks

**N.B.1**: I tested the logic and run a couple of jobs on local cluster as well as tested that previous behavior is not impacted.
**N.B.2**: I will work/update the tests as soon as I get feedback and turn this draft into a PR.

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by architkulkarni — COMMENTED** [review]
This looks good so far, I would give the go-ahead to continue with adding tests! Thanks for the contribution

**Comment by kevin85421** [comment]
Sorry. I have not read #1294 before. I will review it soon before you start working on the tests.

**Review by kevin85421 — COMMENTED** [review]
I noticed that you mention the following in #1294:

> I understand the logic to prevent crashing the creation of the cluster, unfortunately this make using the operator very hard.

Do you mean it's challenging to associate the Kubernetes service's name with the RayCluster custom resources? 

From my observations in production environments, there are typically two scenarios: either a single custom resource within a namespace or numerous custom resources within the same namespace. In the former case, associating the service with the custom resource is straightforward. However, in the latter case, it becomes impossible to link the service's name to a specific custom resource due to the large number of resources.

Hence, the general solution is to associate the Kubernetes service and CR by `label / selector`. You can use the label `ray.io/cluster` to select the corresponding Kubernetes service.

You can take the following screenshot as an example.
Screen Shot 2023-08-14 at 11 03 47 PM

**Comment by mmourafiq** [comment]
@kevin85421 I completely understand that you can look up the service by a selector and also understand the reason of the current logic. However, exposing the service to non-k8s users through a reverse-proxy, e.g. nginx, would require an additional service just to perform the lookup get the correct FQN service, also integrating with other services is a bit challenging because they all require similar lookup.

My current proposal does not break the previous behavior, but, similar to the `JobId`, allows the creation of a deterministic cluster name, which results also of a deterministic service name. In our case all these resources have unique name based on an uuid.

**Comment by mmourafiq** [comment]
@architkulkarni I will add/update the tests and update the status of this PR.

**Comment by kevin85421** [comment]
Take a look at the relationship between: RayJob --> RayCluster --> Pod / Service

1. As demonstrated in https://github.com/ray-project/kuberay/pull/1326#pullrequestreview-1578018567, it is currently easy to associate a Pod or Service with RayCluster.
2. However, there seems to be no label in RayCluster to associate it with RayJob.
3. If we implement (2), we still wouldn't have a method to associate the RayJob with the head service. However, there doesn't seem to be a use case for this association.

I do not recommend allowing users to configure the name of the RayCluster that a RayJob owns if we do not have a very strong use case because:

* Currently, KubeRay has three CRDs, and we should standardize configurations that exhibit similar behaviors. If we enable users to configure RayJob's RayCluster name, it will make the behavior pretty diverge. To elaborate, users will find that:
  * They can configure the RayJob's RayCluster name via a field `RayClusterName`.
  * In RayCluster, you do not have the variable `RayClusterName`, and you should set it in the `metadata.name`.
  * In RayService, users cannot set the `RayClusterName`. During RayService's zero-downtime upgrade, two RayClusters owned by the RayService will coexist in the same namespace simultaneously. However, it's impossible for two RayClusters to have the identical `RayClusterName` within the same namespace. Consequently, this behavior will be distinctly different from that of RayJob.

You can implement (2) if you are interested in it.

**Comment by kevin85421** [comment]
> I completely understand that you can look up the service by a selector and also understand the reason of the current logic. However, exposing the service to non-k8s users through a reverse-proxy, e.g. nginx, would require an additional service just to perform the lookup get the correct FQN service, also integrating with other services is a bit challenging because they all require similar lookup.

Oh, I understand your point. We allow users to configure the entire head service. You can take [this gist](https://gist.github.com/kevin85421/b8e0259467ffdb1b000c4177159f57e9) as an example. It will create a head svc "custom-ray-head-service-name", but currently this has a bug which may be related to [this](https://github.com/ray-project/kuberay/blob/9c28b7de1eefc834d779f35acf5927e8d3c413c4/ray-operator/controllers/ray/common/job.go#L56). If you do not have the bandwidth to fix it, Archit or I can fix it.

```
  rayClusterSpec:
    rayVersion: '2.5.0' # should match the Ray version in the image of the containers
    # Ray head pod template
    headGroupSpec:
      headService:
        metadata:
          name: custom-ray-head-service-name
```

**Comment by mmourafiq** [comment]
That's correct, I tried that before but the operator was not able to reconcile the job, the env vars were always generated automatically, so I assumed that it's only for customizing labels/annotations and not the service name.

If that works then this PR is not needed.

**Comment by kevin85421** [comment]
Open a PR https://github.com/ray-project/kuberay/pull/1332/ and tested it with the gist mentioned above. I will write some unit tests tmr.

**Comment by mmourafiq** [comment]
Closing this draft in favor of #1332

**Pull request closed without merging**
