### PR TITLE
Cherry pick master fixes to 0.3 release

### PR DESCRIPTION
**Pull request by Jeffwan**
## Why are these changes needed?

I cherry-pick recent master fixes and minor features to `release-0.3`. Please have a check. I will cut a `v0.3.0-rc.1` for final testing after this is merged. If there's no additional feedback, we will cut v0.3.0 official release. 

Please help checking anything PRs need to be cherry-picked. 

/cc @DmitriGekhtman @pingsutw @brucez-anyscale @iycheng @wilsonwang371 

## Related issue number
https://github.com/ray-project/kuberay/issues/349

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by Jeffwan** [comment]
image

Not sure what happened on the Github side

**Comment by Jeffwan** [comment]
It's working now. Seems it's just Github's issue

**Comment by Jeffwan** [comment]
@DmitriGekhtman If it looks good to you. I will merge the change. CI works now.

**Review by DmitriGekhtman — APPROVED** [review]

**Review by pingsutw — APPROVED** [review]
lgtm. Thank you, @Jeffwan

**Pull request merged**
