### PR TITLE
separate compatibility from merge request tigger

### PR DESCRIPTION
**Pull request by wilsonwang371**
## Why are these changes needed?

disable compatibility test for merge requests. only run during nightly

## Related issue number

#691 

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [X] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kevin85421** [comment]
Thank @wilsonwang371 for this contribution! Maybe we can use some annotations to skip some flaky tests [1] until we make them stable. Running them nightly just hides the questions deeper. cc @DmitriGekhtman @sihanwang41 @Jeffwan 

[1] https://docs.python.org/3/library/unittest.html#skipping-tests-and-expected-failures

**Comment by wilsonwang371** [comment]
> Thank @wilsonwang371 for this contribution! Maybe we can use some annotations to skip some flaky tests [1] until we make them stable. Running them nightly just hides the questions deeper. cc @DmitriGekhtman @sihanwang41 @Jeffwan
> 
> [1] https://docs.python.org/3/library/unittest.html#skipping-tests-and-expected-failures

The compatibility test is taking a long time and i think it may be a good idea to add more tests instead of running compatibility test which so far is mainly for FT tests. 

On the other hand, we do need the compatibility tests but it may not need to get executed this often.

**Review by scarlet25151 — APPROVED** [review]
This PR move the compatibility test to the check the master branch at 0:00 each day, and when PR is pushed we will skip the compatibility check. LGTM.

**Comment by scarlet25151** [comment]
BTW @wilsonwang371, maybe you can explain more in detail after this modification, what does the compatibility check would be used for, and if failed, what's the work pattern we should follow, for example, how can we find which PR result the failed?

**Comment by kevin85421** [comment]
Thank @wilsonwang371 and @scarlet25151 for the reply! In my opinion, the compatibility-test is time-consuming because we need to retry again and again due to flakiness. If we use annotations to skip flaky tests and keep stable tests, it is not time-consuming. We will pay more time back if we run them nightly (e.g. we need to locate the problematic PR and fix them).

**Comment by wilsonwang371** [comment]
> Thank @wilsonwang371 and @scarlet25151 for the reply! In my opinion, the compatibility-test is time-consuming because we need to retry again and again due to flakiness. If we use annotations to skip flaky tests and keep stable tests, it is not time-consuming. We will pay more time back if we run them nightly (e.g. we need to locate the problematic PR and fix them).

Other than the flaky test, I think there are only 2 or 3 basic tests after a kind cluster is ready. 

We can start writing more tests and put them in the new tests can be triggered by merge requests.

**Comment by kevin85421** [comment]
> > Thank @wilsonwang371 and @scarlet25151 for the reply! In my opinion, the compatibility-test is time-consuming because we need to retry again and again due to flakiness. If we use annotations to skip flaky tests and keep stable tests, it is not time-consuming. We will pay more time back if we run them nightly (e.g. we need to locate the problematic PR and fix them).
> 
> Other than the flaky test, I think there are only 2 or 3 basic tests after a kind cluster is ready.
> 
> We can start writing more tests and put them in the new tests can be triggered by merge requests.

This makes sense. Let me check whether I can use the new configuration test framework (https://github.com/ray-project/kuberay/blob/master/tests/framework/prototype.py) to implement the existing "basic tests". If we can, it is OK to change compatibility tests to run nightly.

**Review by DmitriGekhtman — CHANGES_REQUESTED** [review]
I agree that moving the entire collection of compatibility tests to a once-a-day cron job is too heavy-handed.

It's enough to isolate the problematic tests in a "flakey" test job, which could run per-PR or nightly or both.

**Comment by DmitriGekhtman** [comment]
We opted to de-flake the CI in this PR instead: https://github.com/ray-project/kuberay/pull/759
test_detached_actor appears to still be a bit flakey

**Pull request closed without merging**
