### PR TITLE
[Release] Update docs for release v0.4.0

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?
- [x] https://github.com/ray-project/kuberay/blob/master/docs/deploy/docker.md
- [x] https://github.com/ray-project/kuberay/blob/master/docs/guidance/ingress.md
   - [x] @sihanwang41 will help verify the parts related to NGINX.
   - [ ] I will verify ALB support. => We decide not to verify this document now to avoid conflicts with Ray's release. An user in slack channel said that "Anyone have implemented the ray-cluster in EKS with ALB successfully? I have created the ingress with below ingress.yaml. The Dashboard(port 8265) is working fine and the TargetGroup is healthy." ([Link](https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1669563017212259))
- [x] https://github.com/ray-project/kuberay/blob/master/docs/deploy/installation.md
- [x] https://github.com/ray-project/kuberay/blob/master/docs/development/development.md
- [x] https://github.com/ray-project/kuberay/blob/master/helm-chart/ray-cluster/README.md
- [x] https://github.com/ray-project/kuberay/blob/master/helm-chart/kuberay-operator/README.md

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kevin85421** [comment]
@scarlet25151 would you mind writing a development guide for APIServer and adding the guide to [development.md#develop-kuberay-apiserver](https://github.com/ray-project/kuberay/blob/master/docs/development/development.md#develop-kuberay-apiserver)? If you are busy, we can create an issue to track the progress. Thank you!

**Comment by scarlet25151** [comment]
> @scarlet25151 would you mind writing a development guide for APIServer and adding the guide to [development.md#develop-kuberay-apiserver](https://github.com/ray-project/kuberay/blob/master/docs/development/development.md#develop-kuberay-apiserver)? If you are busy, we can create an issue to track the progress. Thank you!

Hi @kevin85421 thank you for your suggestions, here we've added the `DEVELOPMENT.md` docs for apiserver in https://github.com/ray-project/kuberay/pull/778/files#diff-f2d8dab7dc054250560f0413fa948a52fd11928ed08923a0c9a239d0837bae00, and we may combine them together?

**Comment by kevin85421** [comment]
@DmitriGekhtman I did not have any context related to ArgoCD. What's the priority of reviewing [kuberay-operator/README.md#working-with-argo-cd](https://github.com/ray-project/kuberay/blob/master/helm-chart/kuberay-operator/README.md#working-with-argo-cd)? Thank you!

**Comment by DmitriGekhtman** [comment]
> @DmitriGekhtman I did not have any context related to ArgoCD. What's the priority of reviewing [kuberay-operator/README.md#working-with-argo-cd](https://github.com/ray-project/kuberay/blob/master/helm-chart/kuberay-operator/README.md#working-with-argo-cd)? Thank you!

I wouldn't worry about it. If we get questions about this, we can ping the author.

**Review by DmitriGekhtman — APPROVED** [review]
Looks great to me, thanks!

**Pull request merged**
