### PR TITLE
Adding suppoprt for Ray Serve 2

### PR DESCRIPTION
**Pull request by blublinsky**
## Why are these changes needed?

Current support for serve in the API server was broken and incomplete

## Related issue number

closes https://github.com/ray-project/kuberay/issues/1411

## Checks

- [ x] I've made sure the tests are passing. 
- Testing Strategy
   - [x ] Unit tests
   - [x ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by blublinsky** [comment]
I am not happy with Servev2 support, but it does work
I also provided samples for manual testing

**Comment by z103cb** [comment]
@blublinsky can you update the PR description?

**Comment by z103cb** [comment]
@blublinsky can you also update the commit description ? 

I have tested using the new endpoints using the supplied request. They run to success, the clusters came up yet the ray-serve did not come up correctly. This issue is also present when running the  sample serve config, so I suspect it something else and not this commit.

Once the commit message is updated, I will approve this PR.

**Comment by blublinsky** [comment]
Fixed https://github.com/ray-project/kuberay/issues/1189

**Pull request closed without merging**
