### PR TITLE
fix: typo worker_group_sepc -> worker_group_spec

### PR DESCRIPTION
**Pull request by davidxia**
## Checks

- [x] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by scarlet25151 — COMMENTED** [review]
I notice that there is some other places that have same typo 
[apiserver/pkg/manager/resource_manager.go:L93](https://github.com/ray-project/kuberay/blob/80f19eb9b52ec7fe9e4fde3fbf210e7be200ef39/apiserver/pkg/manager/resource_manager.go#L93)
[apiserver/pkg/util/cluster.go:L45](https://github.com/ray-project/kuberay/blob/7228732dbe3cd3faa1838f9aae35712108058bd6/apiserver/pkg/util/cluster.go#L45)
[apiserver/pkg/server/cluster_server.go:L127](https://github.com/ray-project/kuberay/blob/ea6ee86db2704de61b119a5965146de49aec3484/apiserver/pkg/server/cluster_server.go#L127)
[cli/pkg/cmd/cluster/create.go:L142](https://github.com/ray-project/kuberay/blob/76cdcad8f614d7158d98c767a9424a06fed62936/cli/pkg/cmd/cluster/create.go#L142)
[apiserver/pkg/model/converter.go:L35](https://github.com/ray-project/kuberay/blob/d1e0d1aff846efdd8e502da88f25a35746b2b0ca/apiserver/pkg/model/converter.go#L35)

that part need to be modified to be compatible with the proto changes.

**Comment by davidxia** [comment]
@scarlet25151 thanks, I think I replaced all of them now.

**Review by scarlet25151 — APPROVED** [review]
Overall LGTM now.

**Pull request merged**
