### PR TITLE
Removed use of the  of BUILD_FLAGS in apiserver makefile

### LINKED ISSUE #1335: [Bug] API Server makefile is using build version based on GIT tags, that might not work on the fork, that has no tags
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

apiserver

### What happened + What you expected to happen

All of the make commands produces `fatal: No names found, cannot describe anything.` then it can't find tags. In general, because a makefile is used for local development, this functionality is not required

### Reproduction script

run any make command

### Anything else

Always, if the fork does not have tags

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by z103cb**
Removed use of variables used in building BUILD_FLAGS 

## Why are these changes needed?

When the tags are not available in the git repo the makefile an error is reported.
## Related issue number
Fixes  #1335
Closes #1335 

## Checks

- [X] I've made sure the tests are passing. 
- Testing Strategy
   - [X] Unit tests
   - [X] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by z103cb** [comment]
@blublinsky, @tedhtchang, @scarlet25151
Can you please take a look ?

cc: @kevin85421

**Review by blublinsky — APPROVED** [review]
LGTM

**Review by tedhtchang — APPROVED** [review]
I could not replicated the stated issue; however `make build` did run fine in with or without the change.

**Review by kevin85421 — APPROVED** [review]
LGTM

**Pull request merged**
