### PR TITLE
[Feature][Helm] Align the key of minReplicas and maxReplicas

### PR DESCRIPTION
**Pull request by orcahmlee**
Signed-off-by: Andrew Li <orcahmlee@gmail.com>

## Why are these changes needed?

This PR aligns the `minReplicas` and `maxReplicas`.
Since the RayCluster CRD uses `minReplicas` and `maxReplicas`, the `values.yaml` should use it instead of using `miniReplicas` and `maxiReplicas`

## Checks

- [] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by orcahmlee** [comment]
Hi @DmitriGekhtman ,
Would you mind reviewing this PR?

**Comment by DmitriGekhtman** [comment]
I agree, but we also need to ensure backwards compatibility of existing values.yaml files.

Would you mind modifying the template such that it understands "maxiReplicas"/"miniReplicas" but ignores these fields if "maxReplicas"/"minReplicas" is specified?

@kevin85421 can help with reviewing and getting this merged.

**Review by kevin85421 — COMMENTED** [review]
Thank @orcahmlee for your contribution!

We may also need to update `miniReplicas` and `maxiReplicas` in `values.yaml` to `minReplicas` and `maxReplicas`. Currently, this PR can pass the helm chart lint tests because it uses the `default` functions.

In addition, as @DmitriGekhtman said, we need to keep backward compatibility.

https://github.com/ray-project/kuberay/blob/0adc5084969d6dd769f6af0d3c30e877187aeeab/helm-chart/ray-cluster/values.yaml#L116-L117

**Comment by orcahmlee** [comment]
> Thank @orcahmlee for your contribution!
> 
> We may also need to update `miniReplicas` and `maxiReplicas` in `values.yaml` to `minReplicas` and `maxReplicas`. Currently, this PR can pass the helm chart lint tests because it uses the `default` functions.
> 
> In addition, as @DmitriGekhtman said, we need to keep backward compatibility.

Hi @kevin85421 ,
Would you mind reviewing it again?

**Review by kevin85421 — COMMENTED** [review]
Thank you for the update. Maybe we can use `default` to simplify the logic. You can refer to this commit: https://github.com/kevin85421/kuberay/commit/28138f414d6755c4377bbc4a3d3c113d5bd88191

**Comment by orcahmlee** [comment]
> Maybe we can use `default` to simplify the logic. You can refer to this commit: [kevin85421@28138f4](https://github.com/kevin85421/kuberay/commit/28138f414d6755c4377bbc4a3d3c113d5bd88191)

Thanks for your reminder and kindly sample code. I haven't used the nested `default` function.
I've updated a new commit, please review it.

**Review by kevin85421 — APPROVED** [review]

**Pull request merged**
