### PR TITLE
servev2 support for API server

### PR DESCRIPTION
**Pull request by blublinsky**
## Why are these changes needed?

This cleans up and extends Ray Serve support in the API server to support all of the operator's capabilities

## Related issue number

closes https://github.com/ray-project/kuberay/issues/1411 and https://github.com/ray-project/kuberay/issues/1189

## Checks

- [ x] I've made sure the tests are passing. 
- Testing Strategy
   - [x ] Unit tests
   - [ x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by z103cb** [comment]
This is looking good, but something caught my eye when I was running the serviceV1 sample curl. The response showed something that might confuse the user.

Here's the response I got

```json
{
  "name": "test-v1",
  "namespace": "default",
  "user": "user",
  "serveDeploymentGraphSpec": {
    "importPath": "fruit.deployment_graph",
    "runtimeEnv": "working_dir: \"https://github.com/ray-project/test_dag/archive/c620251044717ace0a4c19d766d43c5099af8a77.zip\"\n",
    "serveConfigs": [
      {
        "deploymentName": "OrangeStand",
        "replicas": 1,
        "userConfig": "price: 2",
        "actorOptions": {
          "cpusPerActor": 0.1
        }
      },
      {
        "deploymentName": "PearStand",
        "replicas": 1,
        "userConfig": "price: 1",
        "actorOptions": {
          "cpusPerActor": 0.1
        }
      },
      {
        "deploymentName": "FruitMarket",
        "replicas": 1,
        "actorOptions": {
          "cpusPerActor": 0.1
        }
      },
      {
        "deploymentName": "DAGDriver",
        "replicas": 1,
        "routePrefix": "/",
        "actorOptions": {
          "cpusPerActor": 0.1
        }
      }
    ]
  },
  "serviceUnhealthySecondThreshold": 900,
  "deploymentUnhealthySecondThreshold": 300,
  "clusterSpec": {
    "headGroupSpec": {
      "computeTemplate": "default-template",
      "image": "rayproject/ray:2.6.3-py310-aarch64",
      "serviceType": "NodePort",
      "rayStartParams": {
        "dashboard-host": "0.0.0.0",
        "metrics-export-port": "8080"
      }
    },
    "workerGroupSpec": [
      {
        "groupName": "small-wg",
        "computeTemplate": "default-template",
        "image": "rayproject/ray:2.6.3-py310-aarch64",
        "replicas": 1,
        "minReplicas": 5,
        "maxReplicas": 1,
        "rayStartParams": {
          "node-ip-address": "$MY_POD_IP"
        }
      }
    ]
  },
  "rayServiceStatus": {
    "rayServiceEvents": [
      {
        "id": "test-v1.178502b0e6cad089",
        "name": "test-v1-test-v1.178502b0e6cad089",
        "createdAt": "2023-09-15T07:43:13Z",
        "firstTimestamp": "2023-09-15T07:43:13Z",
        "lastTimestamp": "2023-09-15T07:58:15Z",
        "reason": "ServiceUnhealthy",
        "message": "The service is in an unhealthy state. Controller will perform a round of actions in 10s.",
        "type": "Normal",
        "count": 24
      },
      {
        "id": "test-v1.178502c168c6bb53",
        "name": "test-v1-test-v1.178502c168c6bb53",
        "createdAt": "2023-09-15T07:44:24Z",
        "firstTimestamp": "2023-09-15T07:44:24Z",
        "lastTimestamp": "2023-09-15T07:44:25Z",
        "reason": "WaitForServeDeploymentReady",
        "message": "Put \"http://test-v1-raycluster-x789v-head-svc.default.svc.cluster.local:52365/api/serve/deployments/\": dial tcp 10.96.27.60:52365: connect: connection refused",
        "type": "Normal",
        "count": 2
      },
      {
        "id": "test-v1.178502c27df7030a",
        "name": "test-v1-test-v1.178502c27df7030a",
        "createdAt": "2023-09-15T07:44:29Z",
        "firstTimestamp": "2023-09-15T07:44:29Z",
        "lastTimestamp": "2023-09-15T08:03:14Z",
        "reason": "WaitForServeDeploymentReady",
        "message": "UpdateDeployments fail: 400 Bad Request ValidationError(model='ServeApplicationSchema', errors=[{'loc': ('deployments', 0, 'max_concurrent_queries'), 'msg': 'ensure this value is greater than 0', 'type': 'value_error.number.not_gt', 'ctx': {'limit_value': 0}}, {'loc': ('deployments', 1, 'max_concurrent_queries'), 'msg': 'ensure this value is greater than 0', 'type': 'value_error.number.not_gt', 'ctx': {'limit_value': 0}}, {'loc': ('deployments', 2, 'max_concurrent_queries'), 'msg': 'ensure this value is greater than 0', 'type': 'value_error.number.not_gt', 'ctx': {'limit_value': 0}}, {'loc': ('deployments', 3, 'max_concurrent_queries'), 'msg': 'ensure this value is greater than 0', 'type': 'value_error.number.not_gt', 'ctx': {'limit_value': 0}}])",
        "type": "Normal",
        "count": 523
      }
    ]
  },
  "createdAt": "2023-09-15T08:07:27Z",
  "deleteAt": "1969-12-31T23:59:59Z"
}
```

The bit that caught my eye was
```json
     {
        "id": "test-v1.178502c27df7030a",
        "name": "test-v1-test-v1.178502c27df7030a",
        "createdAt": "2023-09-15T07:44:29Z",
        "firstTimestamp": "2023-09-15T07:44:29Z",
        "lastTimestamp": "2023-09-15T08:03:14Z",
        "reason": "WaitForServeDeploymentReady",
        "message": "UpdateDeployments fail: 400 Bad Request ValidationError(model='ServeApplicationSchema', errors=[{'loc': ('deployments', 0, 'max_concurrent_queries'), 'msg': 'ensure this value is greater than 0', 'type': 'value_error.number.not_gt', 'ctx': {'limit_value': 0}}, {'loc': ('deployments', 1, 'max_concurrent_queries'), 'msg': 'ensure this value is greater than 0', 'type': 'value_error.number.not_gt', 'ctx': {'limit_value': 0}}, {'loc': ('deployments', 2, 'max_concurrent_queries'), 'msg': 'ensure this value is greater than 0', 'type': 'value_error.number.not_gt', 'ctx': {'limit_value': 0}}, {'loc': ('deployments', 3, 'max_concurrent_queries'), 'msg': 'ensure this value is greater than 0', 'type': 'value_error.number.not_gt', 'ctx': {'limit_value': 0}}])",
        "type": "Normal",
        "count": 523
      }
 ```

Is this something we might want to fix? (i.e If the value is not present set it to default)

**Comment by z103cb** [comment]
LGTM. I approve

**Comment by blublinsky** [comment]
@tedhtchang , @kevin85421 can you, please, approve and merge?

**Review by tedhtchang — APPROVED** [review]
I was able to create a rayservice using the following steps:
1. check out PR
2. make build && make run
3. Create a rayservice using the http requests. Note, it would be nice to test with a valid `serveConfigV2`:
```
curl -X POST 'localhost:8888/apis/v1alpha2/namespaces/default/compute_templates' \
--data '{
  "name": "default-template",
  "namespace": "default",
  "cpu": 1,
  "memory": 1
}'
curl -X 'POST' \
  'http://localhost:8888/apis/v1alpha2/namespaces/default/services' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "name": "rayserve-test",
    "namespace": "default",
    "user": "tedchang",
    "serveConfigV2": "some-config",
    "serviceUnhealthySecondThreshold": "300",
    "deploymentUnhealthySecondThreshold": "300",
    "clusterSpec": {
      "headGroupSpec": {
        "computeTemplate": "default-template",
        "image": "rayproject/ray:2.6.3",
        "serviceType": "NodePort",
        "enableIngress": false,
        "rayStartParams": {
          "dashboard-host": "0.0.0.0"
        },
      "workerGroupSpec": [
        {
          "groupName": "small-wg",
          "computeTemplate": "default-template",
          "image": "rayproject/ray:2.6.3",
          "replicas": 1,
          "rayStartParams": {
            "metrics-export-port": "8080"
          }
        }
      ]
    }
  }
  }'
 
```
Get rayservice should return non empty json object
```
curl -X 'GET' \
  'http://cataract1.fyre.ibm.com:8888/apis/v1alpha2/namespaces/default/services' \
  -H 'accept: application/json'
```

**Comment by blublinsky** [comment]
@kevin85421 its up to you now

**Review by kevin85421 — APPROVED** [review]
I haven't reviewed this PR. The changes are specific to the KubeRay API Server, and it has been approved by IBM folks.

**Pull request merged**
