### PR TITLE
Fixed the issue with jobSubmitter resources

### PR DESCRIPTION
**Pull request by blublinsky**
## Why are these changes needed?
Resources for job submitter were assigned incorrectly, causing and error in e2e test

Resource requests aligned with resource limits

## Checks

- [ x] I've made sure the tests are passing. 
- Testing Strategy
   - [x ] Unit tests
   - [ x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by blublinsky** [comment]
@z103cb fixed the resource issue that we discussed, please approve

cc: @kevin85421

**Review by z103cb — COMMENTED** [review]
Can you augment the existing unit test to cover the bug ?

**Comment by blublinsky** [comment]
@z103cb test expanded

**Review by z103cb — APPROVED** [review]
LGTM

**Comment by blublinsky** [comment]
@kevin85421 , this one is ready to merge, I hope

**Review by kevin85421 — APPROVED** [review]

**Pull request merged**
