### PR TITLE
Updates to the apiserver swagger-ui

### LINKED ISSUE #1343: [Bug]  KubeRay API Server shows the pet store swagger UI>
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

apiserver

### What happened + What you expected to happen

After starting the KubeRay API Server, and navigating to the http://localhost:8888/swagger-ui/, I would expect that the KubeRay API server documentation to be displayed.

See the attached file for more details. 
Screenshot 2023-08-17 at 15 09 47

### Reproduction script

* start the local api server (`make cluster run`)
* Navigate to http://localhost:8888/swagger-ui/

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by z103cb**
Fixes #1343

## Why are these changes needed?
Current implementation of the Kuberay API server present the vanilla pet store implementation in the `/swagger-ui/` endpoint. This PR fixes this issues.

The changes are:
* Update the swagger version to 5.4.2
* Added the correct swagger .json files
* Serve the swagger.json files from the local file system when running the API server from the development machine.

## Related issue number

Closes #1343

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by z103cb — COMMENTED** [review]
@tedhtchang, @kevin85421 and @anishasthana I have closed #1387 in favour of this PR. Please take a look.

**Review by blublinsky — APPROVED** [review]
LGTM

**Review by tedhtchang — APPROVED** [review]
LGTM. I verified the swagger UI working. Steps:
```bash
# run apiserver locally
make run
# Check swagger ui http://localhost:8888/swagger-ui/ in the browser
# Deploy RayCluster using the swagger ui [here](https://github.com/ray-project/kuberay/pull/1387#pullrequestreview-1618535476)
```

**Review by kevin85421 — APPROVED** [review]
I haven't reviewed this PR, but I approved it because it only changes KubeRay API Server and it receives two approvals from IBM / RedHat folks.

**Comment by kevin85421** [comment]
The RayService e2e tests are known to be flaky. It is not related with this PR. Merge this PR.

**Pull request merged**
