### PR TITLE
[Feature] Add a chart-test script to enable chart lint error reproduction on laptop

### LINKED ISSUE #559: [Feature] Pre-push hooks
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

It would be great to have a pre-push hook for the KubeRay repo.
Every lightweight check in the CI should be included as part of the hook.
Things to include:
- Linters (including, if possible, the new Helm check)
- Code and config generation

If the hook modifies code, it should fail.

Guidance on install the hook should be included in the Development README.

### Use case

It is convenient for development to have your push blocked by a pre-push failure.
Otherwise, you have to go to the GitHub UI and wait for checks to run. This slows development iteration speed.

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?
It is used to reproduce the helm chart lint errors on [GitHub Actions](https://github.com/ray-project/kuberay/blob/master/.github/workflows/helm-lint.yaml). If you cannot reproduce the errors on GitHub Actions, the possible reason is the difference versions of Helm. Issue #537 is an example that some errors only happen in old helm versions.

Usage:
* Step1: Install ct (chart-testing) and related dependencies. See https://github.com/helm/chart-testing for more details.
* Step2: `./helm-chart/script/chart-test.sh`

## Related issue number
Part of #559 

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

Screen Shot 2022-09-14 at 11 21 52 AM

### CODE REVIEW

**Comment by kevin85421** [comment]
Hi @DmitriGekhtman,

I should write some documents about this PR, but I am not sure which document is better. Maybe [DEVELOPMENT.md](https://github.com/ray-project/kuberay/blob/master/ray-operator/DEVELOPMENT.md)? Thank you!

**Comment by DmitriGekhtman** [comment]
Yeah, I think development.md is the way to go.

**Comment by DmitriGekhtman** [comment]
This looks good -- please do add a brief section to Development.MD mentioning this test script.

**Comment by kevin85421** [comment]
> This looks good -- but please do add to this PR a brief section to Development.MD mentioning this test script.

Update the document. Thank you!

**Review by DmitriGekhtman — APPROVED** [review]
lgtm

**Pull request merged**
