### PR TITLE
[CLI] Deprecate CLI

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?

* I have never heard of any user using the KubeRay CLI.
* The last CLI code change was 15 months ago ([commit](https://github.com/ray-project/kuberay/pull/361)).
* Some folks active in the KubeRay API Server, @blublinsky and @z103cb, also agree with the deprecation.

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by architkulkarni — COMMENTED** [review]
What is the deprecation plan? Why not print a deprecation warning for one release before deleting it?

**Comment by kevin85421** [comment]
> What is the deprecation plan? Why not print a deprecation warning for one release before deleting it?

I deprecated it because:

(1) I have never heard of any user using the KubeRay CLI.
(2) The last CLI code change was 15 months ago.
(3) The Dependabot reports CVE for the CLI module frequently.

I can add a deprecation warning if it is the Ray community convention.

**Comment by architkulkarni** [comment]
@kevin85421 I checked the Ray convention and [k8s convention](https://kubernetes.io/docs/reference/using-api/deprecation-policy/), and if it's an alpha/experimental feature, then it's okay to remove at any time without warning.  If we consider the CLI to be alpha/experimental, I'm okay with deleting it

**Comment by kevin85421** [comment]
Thanks, @architkulkarni! I will revisit this PR after the v1.0.0 release.

**Comment by kevin85421** [comment]
Run `make release` in the `cli/` to generate releases.

**Pull request closed without merging**
