### PR TITLE
add sidecar container option

### PR DESCRIPTION
**Pull request by akihikokuroda**
## Why are these changes needed?

The sidecar container is useful for adding security capabilities to the pod.  This PR adds the capability to inject the sidecar container to the api-server pod by the values.yaml file.

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by Jeffwan** [comment]
Thanks for the contribution. Do you mind sharing an example?

**Comment by akihikokuroda** [comment]
@Jeffwan Thanks for review!  This is putting the same sidecar capability as the ray head / worker node https://github.com/ray-project/kuberay/blob/056474837cfac5f9917aa8cb76759e8622169027/helm-chart/ray-cluster/templates/raycluster-cluster.yaml#L61.  I can provide a sample soon.

**Comment by akihikokuroda** [comment]
Here is the value file example.  This works with Keycloak configured for "Client Credentials Grant" in OAuth2 specification. 
```
sidecarContainers:
  - image: quay.io/gogatekeeper/gatekeeper:2.1.1
    imagePullPolicy: IfNotPresent
    name: gatekeeper
    args:
    - --no-redirects=true
    - --forwarding-grant-type=client_credentials
    - --listen=0.0.0.0:4180
    - --client-id=rayapiserver
    - --client-secret=APISERVERSECRET-CHANGEME
    - --discovery-url=http://LOCAL-IP:31059/realms/quantumserverless
    - --enable-logging=true
    - --verbose=true
    - --upstream-url=http://kuberay-apiserver-service:8888/
```

**Review by Jeffwan — APPROVED** [review]

**Comment by akihikokuroda** [comment]
@Jeffwan Thanks for your approval.  This change will be used in https://github.com/Qiskit-Extensions/quantum-serverless/pull/235

**Pull request merged**
