### PR TITLE
Update docker images to v0.3.0

### PR DESCRIPTION
**Pull request by Jeffwan**
#349 

## Checks

- [x] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by DmitriGekhtman** [comment]
The tag in ray-operator/config/default/kustomization.yaml also requires an update.

**Comment by Jeffwan** [comment]
@DmitriGekhtman  It's been added. I update it locally and forgot to add to version control. :D

**Review by DmitriGekhtman — APPROVED** [review]
LGTM!
Thanks!!

**Pull request merged**
