### PR TITLE
[Feature] Support environment variables for KubeRay operator chart

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?

I realized that KubeRay operator chart does not support environment variables until https://github.com/ray-project/kuberay/pull/951#issuecomment-1477043319.

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

Screen Shot 2023-03-20 at 4 25 17 PM

```sh
# Update values.yaml
env:
- name: EXAMPLE_ENV
  value: "1"

# Install KubeRay operator
helm install kuberay-operator .

# Check Pod 
kubectl get pods kuberay-operator-ffd776d86-xt248 -o jsonpath='{range .spec.containers[*].env[*]}{@.name}{"="}{@.value}{"\n"}{end}'
# EXAMPLE_ENV=1

# Check Deployment
kubectl get deployments.apps kuberay-operator -o jsonpath='{range .spec.template.spec.containers[*].env[*]}{@.name}{"="}{@.value}{"\n"}{end}'
# EXAMPLE_ENV=1
```

### CODE REVIEW

**Comment by kevin85421** [comment]
cc @Yicheng-Lu-llll @jasoonn

**Comment by Yicheng-Lu-llll** [comment]
LGTM!

I've also tested the changes as follows:

Step 1:
Update the kuberay/helm-chart/kuberay-operator/values.yaml file by adding the following lines:
```yaml
env:
- name: test
  value: 'test-if-works'
```

Step 2:
log the environment variable when Reconciling
```go
# in kuberay/ray-operator/controllers/ray/raycluster_controller.go
func (r *RayClusterReconciler) Reconcile(ctx context.Context, request ctrl.Request) (ctrl.Result, error) {
	var err error
	r.Log.Info("get env var", "test:", os.Getenv("test"))
```

Step 3:
Build a new kuberay image.

Step 4:
Install kuberay using the newly built image by running the following command:
`helm install kuberay-operator --set image.repository=kuberay/operator --set image.tag=nightly .`

Step 5:
Check the logs of the kuberay operator to confirm the environment variable can beaccesed:
`kubectl logs $(kubectl get pods -o=name | grep operator)`

should see the following output:
```shell
root@ip-172-31-14-57:/home/ubuntu/tmp/kuberay# kubectl logs $(kubectl get pods -o=name | grep operator) | grep "get env var"
2023-03-23T04:00:29.487Z        INFO    controllers.RayCluster  get env var     {"test:": "test-if-works"}

```

**Review by gvspraveen — APPROVED** [review]
LGTM.

Can you update PR description with testing instructions like Yicheng comment?

**Comment by kevin85421** [comment]
> LGTM.
> 
> Can you update PR description with testing instructions like Yicheng comment?

Done

**Pull request merged**
