### PR TITLE
[Doc] Add deprecations to ServiceUnhealthySecondThreshold and DeploymentUnhealthySecondThreshold

### PR DESCRIPTION
**Pull request by rueian**
This PR contains the following changes to address the first two points made in the issue https://github.com/ray-project/kuberay/issues/1685:

1. Deprecate those fields in our go source code.
2. Regenerate the `docs/reference/api.md`.
3. Deprecate those fields in the `proto/serve.proto`.
4. Regenerated the `proto/go_client/serve.pb.go`.
5. Skip the lint check of deprecated usages (SA1019) in `apiserver/Makefile`, otherwise it will not pass.
6. Remove `"serviceUnhealthySecondThreshold"` and `"deploymentUnhealthySecondThreshold"` usages in the `apiserver/README.md`.

### CODE REVIEW

**Comment by kevin85421** [comment]
cc @blublinsky @z103cb would you mind reviewing this PR? Thanks!

**Review by blublinsky — APPROVED** [review]
LGTM

**Review by z103cb — APPROVED** [review]
Looking good, approved!

**Review by kevin85421 — APPROVED** [review]
LGTM

**Pull request merged**
