### PR TITLE
Revert "[CRD] Delete CRD v1alpha1 (#1771)"

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?

This reverts commit d723f504eab5e6794597cf5f5df9fa7b18292230 because Kueue has not yet completed v1 support. We will remove v1alpha1 in KubeRay 1.2.0 instead. See https://github.com/kubernetes-sigs/kueue/pull/1435 for more details.

Follow up: Check all CRD changes after d723f504eab5e6794597cf5f5df9fa7b18292230.

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kevin85421** [comment]
cc @alculquicondor

**Comment by tenzen-y** [comment]
Thank the Kuberay team for keeping maintenance v1alpha1 API!

**Review by architkulkarni — APPROVED** [review]

**Comment by alculquicondor** [comment]
Thank you!

**Comment by andrewsykim** [comment]
Thanks @kevin85421 !

**Pull request merged**
