### PR TITLE
Add env variable comment to kuberay-operator

### PR DESCRIPTION
**Pull request by ByronHsu**
## Why are these changes needed?

There are some envs in kuberay to configure its behavior. However, we currently lack the documentation. I add the env and comments in both helm and customization.

## Checks

- [x] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ByronHsu** [comment]
@kevin85421 Could you provide which env we have in the operator?

**Comment by kevin85421** [comment]
The KubeRay operator provides user-facing environment variables such as `CLUSTER_DOMAIN` and `ENABLE_INIT_CONTAINER_INJECTION`. Although there are additional environment variables available, no users have inquired about them yet.

By the way, some users use Kustomize to deploy KubeRay operator (See [here](https://github.com/ray-project/kuberay#use-yaml) for more details). Could you also add the environment variables in the YAML files? Thanks!

**Comment by ByronHsu** [comment]
@kevin85421 updated the pr ^^

**Review by kevin85421 — APPROVED** [review]
LGTM

**Pull request merged**
