### PR TITLE
[WIP] add gcs ha design doc

### PR DESCRIPTION
**Pull request by wilsonwang371**
## Why are these changes needed?

Add design proposal for GCS HA support in KubeRay

## Related issue number

#290

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by wilsonwang371** [comment]
@Jeffwan @DmitriGekhtman we may need to discuss this later in our sync up meeting.

cc @iycheng

**Comment by DmitriGekhtman** [comment]
sgtm, will make sure everyone's in the loop

**Comment by asm582** [comment]
Thanks for sharing the design doc. A few questions, while connecting to the new head node: 
- Will there be an impact on local task execution on worker nodes? 
- Do we know the impact of objects stored in plasma (on the head node)?

**Comment by wilsonwang371** [comment]
> Thanks for sharing the design doc. A few questions, while connecting to the new head node:
> 
> * Will there be an impact on local task execution on worker nodes?

Yes and No. The detail is listed in the GCS FT design document. @iycheng may be able to provide more specification details.

> * Do we know the impact of objects stored in plasma (on the head node)?

In order to make this work, we need external redis as the backend storage.

**Comment by wilsonwang371** [comment]
I added a detailed document in #294 latest patch.

**Pull request closed without merging**
